[package]
name = "hm_with_kinds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gc = "0.4.1"
gc_derive = "0.4.1"